# Generated by Django 3.1.7 on 2021-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='title'),
            preserve_default=False,
        ),
    ]
